// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package snitch_cluster_peripheral_reg_pkg;

    localparam SNITCH_CLUSTER_PERIPHERAL_REG_DATA_WIDTH = 64;
    localparam SNITCH_CLUSTER_PERIPHERAL_REG_MIN_ADDR_WIDTH = 9;
    localparam SNITCH_CLUSTER_PERIPHERAL_REG_SIZE = 'h1c0;
    localparam NumPerfCounters = 'h10;
    localparam NumCtrlScratch = 'h4;

    typedef struct packed {
        logic [31:0] _reserved_63_32;
        logic [15:0] metric;
        logic [15:0] hart;
    } snitch_cluster_peripheral_reg__perf_cnt_sel__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        snitch_cluster_peripheral_reg__perf_cnt_sel__external__fields__in_t rd_data;
        logic wr_ack;
    } snitch_cluster_peripheral_reg__perf_cnt_sel__external__in_t;

    typedef struct packed {
        logic [15:0] _reserved_63_48;
        logic [47:0] perf_counter;
    } snitch_cluster_peripheral_reg__perf_cnt__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        snitch_cluster_peripheral_reg__perf_cnt__external__fields__in_t rd_data;
        logic wr_ack;
    } snitch_cluster_peripheral_reg__perf_cnt__external__in_t;

    typedef struct {
        snitch_cluster_peripheral_reg__perf_cnt_sel__external__in_t perf_cnt_sel[16];
        snitch_cluster_peripheral_reg__perf_cnt__external__in_t perf_cnt[16];
    } snitch_cluster_peripheral_reg__perf_regs__in_t;

    typedef struct {
        logic wr_ack;
    } snitch_cluster_peripheral_reg__cl_clint_set__external__in_t;

    typedef struct {
        logic wr_ack;
    } snitch_cluster_peripheral_reg__cl_clint_clear__external__in_t;

    typedef struct {
        snitch_cluster_peripheral_reg__perf_regs__in_t perf_regs;
        snitch_cluster_peripheral_reg__cl_clint_set__external__in_t cl_clint_set;
        snitch_cluster_peripheral_reg__cl_clint_clear__external__in_t cl_clint_clear;
    } snitch_cluster_peripheral_reg__in_t;

    typedef struct {
        logic value;
    } snitch_cluster_peripheral_reg__perf_cnt_en__enable__out_t;

    typedef struct {
        snitch_cluster_peripheral_reg__perf_cnt_en__enable__out_t enable;
    } snitch_cluster_peripheral_reg__perf_cnt_en__out_t;

    typedef struct packed {
        logic [31:0] _reserved_63_32;
        logic [15:0] metric;
        logic [15:0] hart;
    } snitch_cluster_peripheral_reg__perf_cnt_sel__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        snitch_cluster_peripheral_reg__perf_cnt_sel__external__fields__out_t wr_data;
        snitch_cluster_peripheral_reg__perf_cnt_sel__external__fields__out_t wr_biten;
    } snitch_cluster_peripheral_reg__perf_cnt_sel__external__out_t;

    typedef struct packed {
        logic [15:0] _reserved_63_48;
        logic [47:0] perf_counter;
    } snitch_cluster_peripheral_reg__perf_cnt__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        snitch_cluster_peripheral_reg__perf_cnt__external__fields__out_t wr_data;
        snitch_cluster_peripheral_reg__perf_cnt__external__fields__out_t wr_biten;
    } snitch_cluster_peripheral_reg__perf_cnt__external__out_t;

    typedef struct {
        snitch_cluster_peripheral_reg__perf_cnt_en__out_t perf_cnt_en[16];
        snitch_cluster_peripheral_reg__perf_cnt_sel__external__out_t perf_cnt_sel[16];
        snitch_cluster_peripheral_reg__perf_cnt__external__out_t perf_cnt[16];
    } snitch_cluster_peripheral_reg__perf_regs__out_t;

    typedef struct packed {
        logic [31:0] _reserved_63_32;
        logic [31:0] cl_clint_set;
    } snitch_cluster_peripheral_reg__cl_clint_set__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        snitch_cluster_peripheral_reg__cl_clint_set__external__fields__out_t wr_data;
        snitch_cluster_peripheral_reg__cl_clint_set__external__fields__out_t wr_biten;
    } snitch_cluster_peripheral_reg__cl_clint_set__external__out_t;

    typedef struct packed {
        logic [31:0] _reserved_63_32;
        logic [31:0] cl_clint_clear;
    } snitch_cluster_peripheral_reg__cl_clint_clear__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        snitch_cluster_peripheral_reg__cl_clint_clear__external__fields__out_t wr_data;
        snitch_cluster_peripheral_reg__cl_clint_clear__external__fields__out_t wr_biten;
    } snitch_cluster_peripheral_reg__cl_clint_clear__external__out_t;

    typedef struct {
        logic value;
    } snitch_cluster_peripheral_reg__icache_prefetch_enable__icache_prefetch_enable__out_t;

    typedef struct {
        snitch_cluster_peripheral_reg__icache_prefetch_enable__icache_prefetch_enable__out_t icache_prefetch_enable;
    } snitch_cluster_peripheral_reg__icache_prefetch_enable__out_t;

    typedef struct {
        snitch_cluster_peripheral_reg__perf_regs__out_t perf_regs;
        snitch_cluster_peripheral_reg__cl_clint_set__external__out_t cl_clint_set;
        snitch_cluster_peripheral_reg__cl_clint_clear__external__out_t cl_clint_clear;
        snitch_cluster_peripheral_reg__icache_prefetch_enable__out_t icache_prefetch_enable;
    } snitch_cluster_peripheral_reg__out_t;

    typedef enum logic [4:0] {
        snitch_cluster_peripheral_reg__perf_metric__cycle = 'h0,
        snitch_cluster_peripheral_reg__perf_metric__tcdm_accessed = 'h1,
        snitch_cluster_peripheral_reg__perf_metric__tcdm_congested = 'h2,
        snitch_cluster_peripheral_reg__perf_metric__issue_fpu = 'h3,
        snitch_cluster_peripheral_reg__perf_metric__issue_fpu_seq = 'h4,
        snitch_cluster_peripheral_reg__perf_metric__issue_core_to_fpu = 'h5,
        snitch_cluster_peripheral_reg__perf_metric__retired_instr = 'h6,
        snitch_cluster_peripheral_reg__perf_metric__retired_load = 'h7,
        snitch_cluster_peripheral_reg__perf_metric__retired_i = 'h8,
        snitch_cluster_peripheral_reg__perf_metric__retired_acc = 'h9,
        snitch_cluster_peripheral_reg__perf_metric__dma_aw_stall = 'ha,
        snitch_cluster_peripheral_reg__perf_metric__dma_ar_stall = 'hb,
        snitch_cluster_peripheral_reg__perf_metric__dma_r_stall = 'hc,
        snitch_cluster_peripheral_reg__perf_metric__dma_w_stall = 'hd,
        snitch_cluster_peripheral_reg__perf_metric__dma_buf_w_stall = 'he,
        snitch_cluster_peripheral_reg__perf_metric__dma_buf_r_stall = 'hf,
        snitch_cluster_peripheral_reg__perf_metric__dma_aw_done = 'h10,
        snitch_cluster_peripheral_reg__perf_metric__dma_aw_bw = 'h11,
        snitch_cluster_peripheral_reg__perf_metric__dma_ar_done = 'h12,
        snitch_cluster_peripheral_reg__perf_metric__dma_ar_bw = 'h13,
        snitch_cluster_peripheral_reg__perf_metric__dma_r_done = 'h14,
        snitch_cluster_peripheral_reg__perf_metric__dma_r_bw = 'h15,
        snitch_cluster_peripheral_reg__perf_metric__dma_w_done = 'h16,
        snitch_cluster_peripheral_reg__perf_metric__dma_w_bw = 'h17,
        snitch_cluster_peripheral_reg__perf_metric__dma_b_done = 'h18,
        snitch_cluster_peripheral_reg__perf_metric__dma_busy = 'h19,
        snitch_cluster_peripheral_reg__perf_metric__icache_miss = 'h1a,
        snitch_cluster_peripheral_reg__perf_metric__icache_hit = 'h1b,
        snitch_cluster_peripheral_reg__perf_metric__icache_prefetch = 'h1c,
        snitch_cluster_peripheral_reg__perf_metric__icache_double_hit = 'h1d,
        snitch_cluster_peripheral_reg__perf_metric__icache_stall = 'h1e
    } snitch_cluster_peripheral_reg__perf_metric_e;
endpackage
