# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
<%
    disclaimer = (
        '# AUTOMATICALLY GENERATED by clustergen.py; edit sw/toolchain.mk.tpl or\n'
        '# the configuration instead.'
    )

    cores = [core for hive in cfg['cluster']['hives'] for core in hive['cores']]
    e = any(c['isa_parsed'].e for c in cores)
    zfh = any(c['zfh'] for c in cores)
    xfvec = any(c['xfvec'] for c in cores)
    march_letters = [l for l in ['m', 'a', 'f', 'd', 'v'] if any(getattr(c['isa_parsed'], l) for c in cores)]

    march = 'rv32'
    march += 'e' if e else 'i'
    march += ''.join(march_letters)
    march += '_zfh' if zfh else ''
    march += '_zifencei'

    all_features = ['xssr', 'xfrep', 'xdma', 'xcopift', 'xcvmem',
        'xpulpabs', 'xpulpbitop', 'xpulpbr', 'xpulpclip', 'xpulpmacsi',
        'xpulpminmax', 'xpulpslet', 'xpulpvect', 'xpulpvectshufflepack']
    features = [f for f in all_features if any(c[f] for c in cores)]

    # Features that depend on a combination of configuration parameters
    smallfloat_b = any(c['xf8'] or c['xf8alt'] for c in cores)
    smallfloat_h = any(c['zfh'] or c['xf16alt'] for c in cores)

    if smallfloat_b:
        features.append('xsmallfloatb')
    if smallfloat_h:
        features.append('xsmallfloath')
    if smallfloat_b and xfvec:
        features.append('xsmallfloatvb')
    if smallfloat_h and xfvec:
        features.append('xsmallfloatvh')
    if xfvec and 'f' in march_letters and 'd' in march_letters:
        features.append('xsmallfloatvs')

    attributes = march_letters
    if zfh:
        attributes.append('zfh')
    attributes.append('zifencei')

    mattr = ','.join(f'+{e}' for e in attributes + features)
%>
${disclaimer}

# Sentinel to test that toolchain.mk has been included and read
SN_TOOLCHAIN_MK_READ = 1

# Compiler toolchain
SN_LLVM_BINROOT    ?= $(dir $(shell which riscv32-unknown-elf-clang))
SN_RISCV_CC        ?= $(SN_LLVM_BINROOT)/clang
SN_RISCV_CXX       ?= $(SN_LLVM_BINROOT)/clang++
SN_RISCV_LD        ?= $(SN_LLVM_BINROOT)/ld.lld
SN_RISCV_AR        ?= $(SN_LLVM_BINROOT)/llvm-ar
SN_RISCV_OBJCOPY   ?= $(SN_LLVM_BINROOT)/llvm-objcopy
SN_RISCV_OBJDUMP   ?= $(SN_LLVM_BINROOT)/llvm-objdump
SN_RISCV_MC        ?= $(SN_LLVM_BINROOT)/llvm-mc
SN_RISCV_ADDR2LINE ?= $(SN_LLVM_BINROOT)/llvm-addr2line

# Compiler flags
SN_RISCV_FEATURES = ${' '.join(features)}
SN_RISCV_CFLAGS := -march=${march}
SN_RISCV_CFLAGS += $(foreach feat,$(SN_RISCV_FEATURES),-Xclang -target-feature -Xclang +$(feat))
# Spatz does not support the full RVV ISA, hence we must disable vector code generation
SN_RISCV_CFLAGS += -fno-vectorize -fno-slp-vectorize -mllvm -scalable-vectorization=off -mllvm -combiner-store-merging=false -mllvm -disable-vector-combine
SN_RISCV_CFLAGS += -menable-experimental-extensions
SN_RISCV_CFLAGS += -mabi=ilp32d
SN_RISCV_CFLAGS += -mcmodel=medany
# SN_RISCV_CFLAGS += -mno-fdiv
SN_RISCV_CFLAGS += -fno-builtin-printf
SN_RISCV_CFLAGS += -fno-builtin-sqrtf
SN_RISCV_CFLAGS += -fno-common
SN_RISCV_CFLAGS += -fopenmp
SN_RISCV_CFLAGS += -ftls-model=local-exec
SN_RISCV_CFLAGS += -O3
SN_RISCV_CFLAGS += -Werror
# Disable auto-vectorization so the compiler does not emit RVV instructions
# behind the programmer's back. Can be overridden by setting SN_RISCV_V_FLAGS=.
SN_RISCV_V_FLAGS ?= -fno-vectorize -fno-slp-vectorize -mllvm -scalable-vectorization=off
SN_RISCV_CFLAGS += $(SN_RISCV_V_FLAGS)
ifeq ($(DEBUG), ON)
SN_RISCV_CFLAGS += -g
endif
ifeq ($(OPENOCD_SEMIHOSTING), ON)
SN_RISCV_CFLAGS += -DOPENOCD_SEMIHOSTING
endif

# Linker flags
SN_RISCV_LDFLAGS := -fuse-ld=$(SN_RISCV_LD)
SN_RISCV_LDFLAGS += -nostartfiles
SN_RISCV_LDFLAGS += -nostdlib++
SN_RISCV_LDFLAGS += -lm

# Archiver flags
SN_RISCV_ARFLAGS := rcs

# Objdump flags
SN_RISCV_MATTR_FLAG     = --mattr=${mattr}
SN_RISCV_OBJDUMP_FLAGS := --triple=riscv32 $(SN_RISCV_MATTR_FLAG)
SN_RISCV_OBJDUMP_FLAGS += -D
