# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "snitch"
authors = [
    {name = "Luca Colagrande", email = "colluca@iis.ee.ethz.ch"}
]
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    # Alphabetically sorted.
    "dataclasses",
    "flake8",
    "gitpython",
    "humanize",
    "json5",
    "jsonref",
    "jsonschema",
    "mako",
    "matplotlib",
    "pandas",
    "peakrdl",
    "peakrdl-markdown",
    "peakrdl-rawheader>=0.1.1",
    "prettytable",
    "progressbar2",
    "psutil",
    "pyelftools",
    "pyflexfloat",
    "pymakeutils>=1.4.0",
    "pysynthutils",
    "pytablewriter",
    "pytest",
    "pyyaml",
    "reuse",
    "riscv-opcodes",
    "spatz-vpu @ git+https://github.com/pulp-platform/spatz_vpu.git@0411cc6278d65bf46ca700ec5cde84cd681ce082",
    "tabulate",
    "termcolor",
    "yamllint",
]

[project.optional-dependencies]
kernels  = [
    # Alphabetically sorted.
    "numpy",
    "scikit-learn",
    "torch",
]
docs = [
    "mkdocs",
    "mkdocs-exclude",
    "mkdocs-include-markdown-plugin",
    "mkdocs-macros-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocstrings-python",
]
all = [
    "snitch[kernels,docs]"
]

[dependency-groups]
dev = [
    "tsunami-wave @ git+https://github.com/zarubaf/tsunami.git@4a2d5c02462875fcebaef6f4e84563eb28b99cf8",
]

[tool.uv.sources]
riscv-opcodes = { path = "sw/deps/riscv-opcodes", editable = true }
torch = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.setuptools.package-dir]
"snitch.dnn" = "sw/kernels/dnn"
"snitch.blas" = "sw/kernels/blas"
"snitch.util" = "util"

[tool.pytest.ini_options]
testpaths = ["util/bench/tests"]
