# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

extends: default

rules:
  document-start: disable
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      Bender.yml
      workflows/lint.yml
  colons:
    ignore: |
      Bender.yml
  braces:
    ignore: |
      Bender.yml
  commas:
    ignore: |
      Bender.yml
