// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

module snitch_spatz
  import spatz_pkg::*;
  import rvv_pkg::*;
  import fpnew_pkg::*;
  import cc_pkg::*;
#(
  parameter int unsigned NrMemPorts          = 1,
  parameter int unsigned NumOutstandingLoads = 8,
  parameter fpu_implementation_t FPUImplementation = fpu_implementation_t'(0),
  parameter int unsigned AddrWidth           = 32,
  parameter bit EnableDca                    = 1'b0,
  parameter bit RegisterRsp                  = 1'b0,
  parameter type dreq_t                      = logic,
  parameter type drsp_t                      = logic,
  parameter type spatz_mem_req_t             = logic,
  parameter type spatz_mem_rsp_t             = logic,
  parameter type x_issue_req_t               = logic,
  parameter type x_issue_resp_t              = logic,
  parameter type x_register_t                = logic,
  parameter type x_commit_t                  = logic,
  parameter type x_result_t                  = logic,
  parameter type dca_req_t                   = logic,
  parameter type dca_rsp_t                   = logic,
  parameter type pace_cfg_t                  = logic,
  parameter pace_cfg_t PaceCfg               = '0,
  parameter int unsigned PaceParamWidth      = 0
) (
  input  logic                              clk_i,
  input  logic                              rst_ni,
  input  logic                              testmode_i,
  input  logic [31:0]                       hart_id_i,
  input  logic                              x_issue_valid_i,
  output logic                              x_issue_ready_o,
  input  x_issue_req_t                      x_issue_req_i,
  output x_issue_resp_t                     x_issue_resp_o,
  input  logic                              x_register_valid_i,
  output logic                              x_register_ready_o,
  input  x_register_t                       x_register_i,
  input  logic                              x_commit_valid_i,
  input  x_commit_t                         x_commit_i,
  output logic                              x_result_valid_o,
  input  logic                              x_result_ready_i,
  output x_result_t                         x_result_o,
  output spatz_mem_req_t   [NrMemPorts-1:0] spatz_mem_req_o,
  output logic             [NrMemPorts-1:0] spatz_mem_req_valid_o,
  input  logic             [NrMemPorts-1:0] spatz_mem_req_ready_i,
  input  spatz_mem_rsp_t   [NrMemPorts-1:0] spatz_mem_rsp_i,
  input  logic             [NrMemPorts-1:0] spatz_mem_rsp_valid_i,
  output logic             [1:0]            spatz_mem_finished_o,
  output logic             [1:0]            spatz_mem_str_finished_o,
  input  logic [cc_pkg::iomsb(PaceParamWidth):0] pace_param_i,
  input  fpnew_pkg::pace_mode_t             pace_mode_i,
  output dreq_t                             fp_lsu_mem_req_o,
  input  drsp_t                             fp_lsu_mem_rsp_i,
  input  roundmode_e                        fpu_rnd_mode_i,
  input  fmt_mode_t                         fpu_fmt_mode_i,
  output status_t                           fpu_status_o,
  input  dca_req_t                          dca_req_i,
  output dca_rsp_t                          dca_rsp_o
);

  spatz #(
    .NrMemPorts         (NrMemPorts),
    .NumOutstandingLoads(NumOutstandingLoads),
    .FPUImplementation  (FPUImplementation),
    .AddrWidth          (AddrWidth),
    .EnableDca          (EnableDca),
    .RegisterRsp        (RegisterRsp),
    .dreq_t             (dreq_t),
    .drsp_t             (drsp_t),
    .spatz_mem_req_t    (spatz_mem_req_t),
    .spatz_mem_rsp_t    (spatz_mem_rsp_t),
    .x_issue_req_t      (x_issue_req_t),
    .x_issue_resp_t     (x_issue_resp_t),
    .x_register_t       (x_register_t),
    .x_commit_t         (x_commit_t),
    .x_result_t         (x_result_t),
    .pace_cfg_t         (pace_cfg_t),
    .PaceCfg            (PaceCfg)
  ) i_spatz (
    .clk_i                   (clk_i),
    .rst_ni                  (rst_ni),
    .testmode_i              (testmode_i),
    .hart_id_i               (hart_id_i),
    .x_issue_valid_i         (x_issue_valid_i),
    .x_issue_ready_o         (x_issue_ready_o),
    .x_issue_req_i           (x_issue_req_i),
    .x_issue_resp_o          (x_issue_resp_o),
    .x_register_valid_i      (x_register_valid_i),
    .x_register_ready_o      (x_register_ready_o),
    .x_register_i            (x_register_i),
    .x_commit_valid_i        (x_commit_valid_i),
    .x_commit_i              (x_commit_i),
    .x_result_valid_o        (x_result_valid_o),
    .x_result_ready_i        (x_result_ready_i),
    .x_result_o              (x_result_o),
    .spatz_mem_req_o         (spatz_mem_req_o),
    .spatz_mem_req_valid_o   (spatz_mem_req_valid_o),
    .spatz_mem_req_ready_i   (spatz_mem_req_ready_i),
    .spatz_mem_rsp_i         (spatz_mem_rsp_i),
    .spatz_mem_rsp_valid_i   (spatz_mem_rsp_valid_i),
    .spatz_mem_finished_o    (spatz_mem_finished_o),
    .spatz_mem_str_finished_o(spatz_mem_str_finished_o),
    .pace_param_i            (pace_param_i),
    .pace_mode_i             (pace_mode_i),
    .fp_lsu_mem_req_o        (fp_lsu_mem_req_o),
    .fp_lsu_mem_rsp_i        (fp_lsu_mem_rsp_i),
    .fpu_rnd_mode_i          (fpu_rnd_mode_i),
    .fpu_fmt_mode_i          (fpu_fmt_mode_i),
    .fpu_status_o            (fpu_status_o),
    .dca_req_i               (dca_req_i),
    .dca_rsp_o               (dca_rsp_o)
  );

endmodule
