#--------------------------------------------
# Core Snitch Components
#--------------------------------------------
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/mem_interface/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/tcdm_interface/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/include
+incdir+/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/include
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/rtl/tc_sram.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/rtl/tc_sram_impl.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/rtl/tc_clk.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/cluster_pwr_cells.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/generic_memory.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/generic_rom.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/pad_functional.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/pulp_buffer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/pulp_pwr_cells.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/tc_pwr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/pulp_clock_gating_async.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/cluster_clk_cells.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/tech_cells_generic-1282165f7b690985/src/deprecated/pulp_clk_cells.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/binary_to_gray.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cb_filter_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cc_onehot.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cf_math_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/clk_int_div.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/delta_counter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/ecc_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/edge_propagator_tx.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/exp_backoff.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/fifo_v3.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/gray_to_binary.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/isochronous_4phase_handshake.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/isochronous_spill_register.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/lfsr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/lfsr_16bit.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/lfsr_8bit.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/mv_filter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/onehot_to_bin.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/plru_tree.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/popcount.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/rr_arb_tree.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/rstgen_bypass.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/serial_deglitch.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/shift_reg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/shift_reg_gated.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/spill_register_flushable.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_filter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_fork.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_intf.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_join.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_throttle.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/lossy_valid_to_stream.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/sub_per_hash.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/sync.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/sync_wedge.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/unread.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/read.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_reset_ctrlr_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/clk_int_div_static.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/addr_decode_napot.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_2phase.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_4phase.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/addr_decode.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cb_filter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_fifo_2phase.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/counter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/ecc_decode.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/ecc_encode.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/edge_detect.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/lzc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/max_counter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/rstgen.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/spill_register.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_delay.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_fifo.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_fork_dynamic.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/clk_mux_glitch_free.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_reset_ctrlr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_fifo_gray.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/fall_through_register.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/id_queue.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_to_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_arbiter_flushable.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_fifo_optimal_wrap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_register.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_xbar.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_fifo_gray_clearable.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/cdc_2phase_clearable.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/mem_to_banks.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_arbiter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/stream_omega_net.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/clock_divider_counter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/clk_div.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/find_first_one.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/generic_LFSR_8bit.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/generic_fifo.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/prioarbiter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/pulp_sync.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/pulp_sync_wedge.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/rrarbiter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/clock_divider.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/fifo_v2.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/deprecated/fifo_v1.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/edge_propagator_ack.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/edge_propagator.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/common_cells-02aa01ee4a3b2e52/src/edge_propagator_rx.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_intf.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_err_slv.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_regs.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_cdc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/apb-0b8df27abad700ff/src/apb_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_intf.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_atop_filter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_burst_splitter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_bus_compare.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_cdc_dst.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_cdc_src.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_cut.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_delayer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_dw_downsizer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_dw_upsizer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_fifo.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_id_remap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_id_prepend.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_isolate.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_join.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_dw_converter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_from_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_join.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_lfsr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_mailbox.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_regs.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_to_apb.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_to_axi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_modify_address.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_rw_join.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_rw_split.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_serializer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_slave_compare.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_throttle.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_to_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_cdc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_err_slv.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_dw_converter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_from_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_id_serialize.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lfsr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_multicut.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_to_axi_lite.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_to_mem_banked.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_to_mem_interleaved.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_to_mem_split.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_iw_converter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_lite_xbar.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_xbar.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi-10c18867bc585e38/src/axi_xp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/defs_div_sqrt_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/iteration_div_sqrt_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/control_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/norm_div_sqrt_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/preprocess_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/nrbd_nrsc_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/div_sqrt_top_mvp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpu_div_sqrt_mvp-ca8b2349afb6712f/hdl/div_sqrt_mvp_wrapper.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_res_tbl.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_amos_alu.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_amos.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_lrsc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_atomics.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_lrsc_wrap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_amos_wrap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/axi_riscv_atomics-360637610c0ab464/src/axi_riscv_atomics_wrap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_cast_multi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_classifier.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_divsqrt_multi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_fma.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_fma_multi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_sdotp_multi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_sdotp_multi_wrapper.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_noncomp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_opgroup_block.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_opgroup_fmt_slice.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_opgroup_multifmt_slice.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_rounding.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/fpnew-afcaf014ef5047df/src/fpnew_top.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_intf.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/apb_to_reg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/axi_to_reg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/periph_to_reg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_cdc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_err_slv.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_to_apb.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_to_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_uniform.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/reg_to_tlul.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/vendor/lowrisc_opentitan/src/prim_subreg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/register_interface-f4ec7adf92a180e1/src/axi_lite_to_reg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/debug_rom/debug_rom.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/debug_rom/debug_rom_one_scratch.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_csrs.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dmi_cdc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dmi_jtag_tap.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_sba.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_top.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dmi_jtag.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/.bender/git/checkouts/riscv-dbg-4d2e83f8d49c3adc/src/dm_obi_top.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/mem_to_axi_lite.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/idma_reg64_frontend_reg_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/idma_tf_id_gen.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/dma/axi_dma_data_path.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/axi_interleaved_xbar.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/axi_zero_mem.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/idma_reg64_frontend_reg_top.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/idma_reg64_frontend.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/dma/axi_dma_data_mover.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/dma/axi_dma_burst_reshaper.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/future/src/dma/axi_dma_backend.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_intf.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/axi_to_reqrsp.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_cut.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_demux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_iso.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/reqrsp_interface/src/reqrsp_to_axi.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/mem_interface/src/mem_wide_narrow_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/mem_interface/src/mem_interface.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/tcdm_interface/src/tcdm_interface.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/tcdm_interface/src/axi_to_tcdm.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/tcdm_interface/src/reqrsp_to_tcdm.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/tcdm_interface/src/tcdm_mux.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch_pma_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/riscv_instr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch_regfile_ff.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch_lsu.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch_l0_tlb.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch/src/snitch.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_vm/src/snitch_ptw.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_dma/src/axi_dma_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_dma/src/axi_dma_error_handler.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_dma/src/axi_dma_perf_counters.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_dma/src/axi_dma_twod_ext.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_dma/src/axi_dma_tc_snitch_fe.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_l0.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_refill.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_lfsr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_lookup.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache_handler.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_icache/src/snitch_icache.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ipu/src/snitch_ipu_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ipu/src/snitch_ipu_alu.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ipu/src/snitch_int_ss.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_switch.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_credit_counter.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_indirector.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_intersector.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_addr_gen.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_ssr/src/snitch_ssr_streamer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_amo_shim.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg_pkg.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg_top.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_fpu.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_sequencer.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_tcdm_interconnect.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_barrier.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_fp_ss.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_shared_muldiv.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_cc.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_clkdiv2.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_hive.sv
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snitch_cluster/src/snitch_cluster.sv

#--------------------------------------------
# Snax components
#--------------------------------------------
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snax_shell/src/snax_shell.sv


#--------------------------------------------
# Snax testbenches
#--------------------------------------------
/users/micas/rantonio/no_backup/rga-workspace/snitch_cluster/hw/snax_shell/test/tb/tb_snax_shell_wb.sv